### ISSUE TITLE
the vuejsOidcClient can't connect this project

### ISSUE THREAD

**Issue by bigbirdhzp** [joaojosefilho/IdentityServer4AndApi#1]
Thank you for providing this example!
I always use JS, never use c#.Please forgive me.
I try to run your project with the two username: Claire and Frank,it's ok.But the vuejs example you provide is not connect the IdentityServer4AndApi.
So please give me some guide,thanks!

**Comment by joaojosefilho** [comment]
You need to run the IdentityServer4AndApi project and then the vuejsOidcClient. Maybe your url is different from my.

On the homepage there is a link called discovery document. On this page there is an attribute called issuer. What is the value of this attribute?

In my projet the value is:
`issuer : https://localhost:44321`

**Comment by bigbirdhzp** [comment]
Thanks for you help!
I check my IIS Express port setting.It use the default port.So I try to set use SSL and set the SSL port.
Here is the IdentityServer4.API SSL port I set:
![image](https://user-images.githubusercontent.com/22903159/49054603-b6db2500-f22f-11e8-9572-aa1baefc851e.png)

Here is the IdentityServer4.IDP SSL port I set:
![image](https://user-images.githubusercontent.com/22903159/49054627-cd817c00-f22f-11e8-897d-90ca81677e71.png)

the SSL setting method is: click the Properties > launchSettings.json.

Here is the IdentityServer4.API launchSettings.json:
![image](https://user-images.githubusercontent.com/22903159/49054726-28b36e80-f230-11e8-8c57-e5af16e383d4.png)

Here is the IdentityServer4.IDP launchSettings.json:
![image](https://user-images.githubusercontent.com/22903159/49054753-4385e300-f230-11e8-80b1-1dc25fce852a.png)

**Comment by joaojosefilho** [comment]
Good, now you need to copy a URL with ssl to the url field

![depurar](https://user-images.githubusercontent.com/10532267/49056236-b0ba5980-f1d9-11e8-866a-06bd14c37870.png)

You have to run the project with the URL https://44322/.

![is4](https://user-images.githubusercontent.com/10532267/49055952-5076e800-f1d8-11e8-9b10-5609c2e1502a.png)

Do the same thing with IdentityServer4.API. 

Prints of IdentityServer4.API:

![apidepurar](https://user-images.githubusercontent.com/10532267/49056489-a482cc00-f1da-11e8-8aba-97c77d4f0a6e.png)

![apitela](https://user-images.githubusercontent.com/10532267/49056494-a77dbc80-f1da-11e8-827d-4f68b79fe3d7.png)


In the vuejsOidcClient project, you need to set up the mgr variable with the data from your identity provider(IdentityServer4). configure a variavel mgr no script  SecurityService.js (https://github.com/joaojosefilho/vuejsOidcClient/blob/master/src/services/SecurityService.js)

```
var mgr = new Oidc.UserManager({
  userStore: new Oidc.WebStorageStateStore(),  
  authority: 'https://localhost:44321',
  client_id: 'vuejsclient',
  redirect_uri: window.location.origin + '/static/callback.html',
  response_type: 'id_token token',
  scope: 'openid profile address roles identityserver4api country subscriptionlevel offline_access',
  post_logout_redirect_uri: window.location.origin + '/index.html',
  silent_redirect_uri: window.location.origin + '/static/silent-renew.html',
  accessTokenExpiringNotificationTime: 10,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true
})
```
you need to update the variables according to your identity provider
 - authority:  https://44322/
 -  client_id
 - scope

**Comment by joaojosefilho** [comment]
Configure your statup.cs from the IdentityServer4.api project. Enter the URL of IdentityServer4.IDP

https://github.com/joaojosefilho/IdentityServer4AndApi/blob/master/IdentityServer4.API/Startup.cs

![api](https://user-images.githubusercontent.com/10532267/49056744-b9139400-f1db-11e8-8a76-f93b8893d044.png)

your URL: https://localhost:44322/

**Comment by bigbirdhzp** [comment]
Thanks for your help!
Now I change the ports to the same ones as yours.The API port is 44390.The IDP port is 44321.

Situation 1:
Here is the SecurityService.js:
![image](https://user-images.githubusercontent.com/22903159/49127006-ae313000-f2bd-11e8-830b-856161b23940.png)

Here is the ApiService.js:
![image](https://user-images.githubusercontent.com/22903159/49127031-c43ef080-f2bd-11e8-892c-7d80b510cdfa.png)

Here is the IdentityServer4.API/Startup.cs
![image](https://user-images.githubusercontent.com/22903159/49127102-f2bccb80-f2bd-11e8-8e51-d44f5d777342.png)

I run the project, and I click "GetAll",  success
![image](https://user-images.githubusercontent.com/22903159/49127143-1d0e8900-f2be-11e8-97ce-1585203071e7.png)

this situation has a question: I must clear the browser cache that can success "GetAll", if not ,it will failed.

Situation 2:
I follow your guide and your code , update my SecurityService.js:
![image](https://user-images.githubusercontent.com/22903159/49127258-9b6b2b00-f2be-11e8-8363-f7b0245a9027.png)

authority:https://localhost:44390
client_id:vuejsclient
scope:openid profile address roles identityserver4api country subscriptionlevel

Here is the ApiService.js
![image](https://user-images.githubusercontent.com/22903159/49127374-00bf1c00-f2bf-11e8-987c-580f628f9608.png)

Here is the IdentityServer4.API/Startup.cs
![image](https://user-images.githubusercontent.com/22903159/49127532-8c38ad00-f2bf-11e8-8882-0cd5a558cc24.png)

Run the project. The vue project is 404,because it can not finde the website:
![image](https://user-images.githubusercontent.com/22903159/49127577-c73ae080-f2bf-11e8-99ec-2becc280aa89.png)

So I change the SecurityServices.js:
the authority I change to the "https://localhost:44321".Run the vue project ,it work.

Now I click "GetAll", it cause the error 500:
![image](https://user-images.githubusercontent.com/22903159/49127696-4203fb80-f2c0-11e8-99b7-096e25f30ef1.png)

I find your code ,only one client_id I find, is "vuejsclient".

So here is the summary:
1、Situation 1 is success？
2、What's the new client_id ?
3、I must clear the brower cache, the information can be able to refresh.
     (Every time i run the project,login in, i always click the Scopes to check the scope.I find I have changed the scope, the website Scopes still never refresh.I clear the brower cache, login again, the Scopes refresh.)

**Comment by joaojosefilho** [comment]
I will do a step by step modifying my project

## I changed the URL of the project IdentityServer4.IDP
![buildidp](https://user-images.githubusercontent.com/10532267/49163106-12c6ac00-f30b-11e8-8a74-a3ff9d7e9090.png)

## I changed the URL of the project IdentityServer4.API
![buildapi](https://user-images.githubusercontent.com/10532267/49163514-03942e00-f30c-11e8-8c8d-377ce51448c6.png)

## I changed the class config.cs (https://github.com/joaojosefilho/IdentityServer4AndApi/blob/master/IdentityServer4.IDP/Config.cs)

## Add new scopes. - config.cs
For this example, I'm going to add the "test" scope

```
return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Address(),
                new IdentityResource("roles","Your role(s)", new List<string>(){"role"}),
                new IdentityResource("country","Your country you're living in", new List<string>(){"country"}),
                new IdentityResource("subscriptionlevel","Your subscription level", new List<string>(){"subscriptionlevel"}),
                new IdentityResource("test","A test", new List<string>(){"test"})//I added this line
            };
```

```
AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Address,
                        "roles",
                        "identityserver4api",
                        "country",
                        "subscriptionlevel",
                        "test" //I added this line
                    }
```

## I changed the client_id - config.cs
```
ClientName = "jjfilho", //I modified this line
ClientId = "jjfilhoclient", //I modified this line
```

## I changed the API - config.cs

```
public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource("jjfilhoapi","IndentityServer4 API", new List<string>(){"role"})//I modified this line
                {
                    ApiSecrets = { new Secret("jjfilhosecret".Sha256())}//I modified this line
                }
            };
        }
```

modify the api name
```
AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Address,
                        "roles",
                        "jjfilhoapi",
                        "country",
                        "subscriptionlevel",
                        "test" //I added this line
                    }
```


## I changed the API - Startup.cs (https://github.com/joaojosefilho/IdentityServer4AndApi/blob/master/IdentityServer4.API/Startup.cs)
```
services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {           
                   options.Authority = "https://localhost:44378/"; //I modified this line, URL: IndentityServer4.IDP
                   options.ApiName = "jjfilhoapi"; //I modified this line
                   options.ApiSecret = "jjfilhosecret"; //I modified this line                     
                });
```

## Run the Project
![newurlidp](https://user-images.githubusercontent.com/10532267/49165222-7521ab80-f30f-11e8-9de9-17945dc7e691.png)

![newurlidp](https://user-images.githubusercontent.com/10532267/49165377-c5007280-f30f-11e8-8389-01f8b508e728.png)

![newurlidp](https://user-images.githubusercontent.com/10532267/49165654-72738600-f310-11e8-8894-c7f1e6246934.png)

## I changed the project VueOidcClient (https://github.com/joaojosefilho/vuejsOidcClient/blob/master/src/services/SecurityService.js)

I updated the fields authority, client_id and scope
```
var mgr = new Oidc.UserManager({
  userStore: new Oidc.WebStorageStateStore(),  
  authority: 'https://localhost:44378', **//I modified this line**
  client_id: 'jjfilhoClient', //I modified this line
  redirect_uri: window.location.origin + '/static/callback.html',
  response_type: 'id_token token',
  scope: 'openid profile address roles jjfilhoapi country subscriptionlevel test offline_access', **//I modified this line**
  post_logout_redirect_uri: window.location.origin + '/index.html',
  silent_redirect_uri: window.location.origin + '/static/silent-renew.html',
  accessTokenExpiringNotificationTime: 10,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true
})
```

## I changed the ApiService.js
https://github.com/joaojosefilho/IdentityServer4AndApi/blob/master/IdentityServer4.API/Startup.cs
`const baseUrl = 'https://localhost:44330/api/';`

**Comment by joaojosefilho** [comment]
If you change the scope in the backend, you need to sign out and log in again to renew the access token

**Comment by joaojosefilho** [comment]
Do you still have any questions?

**Comment by bigbirdhzp** [comment]
I am sorry to late to replay.I am doing othe urgent things during these days. I read the identityServer4 document again, read your guide text and follow your step .I konw that I have successed 4days ago, and I already knew what happend i am.Thank you for your patience！
